import { customAlphabet } from 'nanoid'

// 12 字符，base62（字母+数字），冲突概率足够低
const nano = customAlphabet('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', 12)

export const newAgentId = () => `ag_${nano()}`
export const newConversationId = () => `conv_${nano()}`
export const newMessageId = () => `msg_${nano()}`
export const newArtifactId = () => `art_${nano()}`
export const newArtifactSemanticDiffId = () => `asd_${nano()}`
export const newWorkspaceId = () => `ws_${nano()}`
export const newRunId = () => `run_${nano()}`
export const newToolCallId = () => `call_${nano()}`
export const newAttachmentId = () => `att_${nano()}`
export const newPendingWriteId = () => `pwr_${nano()}`
export const newPendingBashCommandId = () => `pbc_${nano()}`
export const newPendingQuestionId = () => `pq_${nano()}`
export const newPendingDispatchPlanId = () => `pdp_${nano()}`
export const newContextSummaryId = () => `ctx_${nano()}`
export const newDeploymentId = () => `dep_${nano()}`
export const newModelProfileId = () => `mp_${nano()}`
export const newNetworkProfileId = () => `net_${nano()}`
export const newCliProfileId = () => `cli_${nano()}`
export const newCliRunId = () => `clirun_${nano()}`
export const newModelConnectionTestId = () => `mct_${nano()}`
export const newModelRouteDecisionId = () => `mrd_${nano()}`
export const newToolConnectionId = () => `tc_${nano()}`
export const newMcpServerId = () => `mcp_${nano()}`
export const newMcpToolDefinitionId = () => `mcpt_${nano()}`
export const newMcpToolCallId = () => `mcpcall_${nano()}`
export const newPromptTemplateId = () => `pt_${nano()}`
export const newPromptTemplateVersionId = () => `ptv_${nano()}`
export const newContextCompressorPolicyId = () => `ccpol_${nano()}`
export const newContextCompressionPlanId = () => `cpln_${nano()}`
export const newPromptDriftMonitorId = () => `pdm_${nano()}`
export const newModelBehaviorSnapshotId = () => `mbs_${nano()}`
export const newPromptDriftRunId = () => `pdr_${nano()}`
export const newDualModelVerificationId = () => `dmv_${nano()}`
export const newAgentConsensusVoteId = () => `acv_${nano()}`
export const newAdversarialReviewId = () => `arv_${nano()}`
export const newContentSafetyPolicyId = () => `csp_${nano()}`
export const newContentSafetyScanId = () => `css_${nano()}`
export const newCopyrightCheckId = () => `cck_${nano()}`
export const newTrustCalibrationPolicyId = () => `tcp_${nano()}`
export const newTrustCalibrationEvaluationId = () => `tce_${nano()}`
export const newBudgetPolicyId = () => `bpol_${nano()}`
export const newBudgetEvaluationId = () => `beval_${nano()}`
export const newConfigVersionId = () => `cfgv_${nano()}`
export const newConfigExportId = () => `cfgx_${nano()}`
export const newConfigImpactAnalysisId = () => `cfgi_${nano()}`
export const newOptimisticLockId = () => `olk_${nano()}`
export const newEditConflictId = () => `ecf_${nano()}`
export const newExportPackageId = () => `pkg_${nano()}`
export const newPackageImportCheckId = () => `pic_${nano()}`
export const newSecretId = () => `sec_${nano()}`
export const newCredentialScopeId = () => `cred_${nano()}`
export const newSandboxPolicyId = () => `sbx_${nano()}`
export const newAuditLogId = () => `aud_${nano()}`
export const newSecurityFindingId = () => `sf_${nano()}`
export const newMetricPointId = () => `met_${nano()}`
export const newExternalMonitoringConfigId = () => `emc_${nano()}`
export const newAlertRuleId = () => `alr_${nano()}`
export const newAlertEventId = () => `ale_${nano()}`
export const newDebugReplaySnapshotId = () => `drs_${nano()}`
export const newAgentHealthScoreId = () => `ahs_${nano()}`
export const newAgentReputationReviewId = () => `arr_${nano()}`
export const newAgentReputationSnapshotId = () => `ars_${nano()}`
export const newAgentProbationRecordId = () => `apb_${nano()}`
export const newAgentEnvironmentPromotionId = () => `aep_${nano()}`
export const newProgrammaticApiKeyId = () => `pak_${nano()}`
export const newSdkTaskId = () => `sdt_${nano()}`
export const newWebhookSubscriptionId = () => `whs_${nano()}`
export const newWebhookDeliveryId = () => `whd_${nano()}`
export const newMultimodalInputId = () => `mmi_${nano()}`
export const newMultimodalOutputId = () => `mmo_${nano()}`
export const newNotificationId = () => `ntf_${nano()}`
export const newNotificationPreferenceId = () => `np_${nano()}`
export const newRetentionPolicyId = () => `rp_${nano()}`
export const newStorageQuotaSnapshotId = () => `sqs_${nano()}`
export const newDataMaintenancePolicyId = () => `dmp_${nano()}`
export const newDataMaintenanceRunId = () => `dmr_${nano()}`
export const newMemoryIntegrityPolicyId = () => `migp_${nano()}`
export const newMemoryIntegrityEvaluationId = () => `mige_${nano()}`
export const newNfrRequirementId = () => `nfr_${nano()}`
export const newNfrEvaluationId = () => `nfre_${nano()}`
export const newKnownLimitationId = () => `klm_${nano()}`
export const newLimitationAcknowledgementId = () => `kla_${nano()}`
export const newPiiMarkerId = () => `pii_${nano()}`
export const newDataExportManifestId = () => `dem_${nano()}`
export const newFeatureFlagId = () => `ff_${nano()}`
export const newFeatureFlagEvaluationId = () => `ffe_${nano()}`
export const newDegradationPolicyId = () => `dgp_${nano()}`
export const newDegradationEventId = () => `dge_${nano()}`
export const newCapabilityIndexEntryId = () => `cap_${nano()}`
export const newKnowledgeGraphNodeId = () => `kgn_${nano()}`
export const newKnowledgeGraphEdgeId = () => `kge_${nano()}`
export const newCapabilityRecommendationId = () => `car_${nano()}`
export const newAutonomyDecisionId = () => `ad_${nano()}`
export const newDynamicPermissionGrantId = () => `dpg_${nano()}`
export const newVoiceInterfaceProfileId = () => `vip_${nano()}`
export const newVoiceConversationTurnId = () => `vct_${nano()}`
export const newE2EEncryptionPolicyId = () => `e2e_${nano()}`
export const newE2EEncryptionCheckId = () => `e2ec_${nano()}`
export const newConcurrencyProfileId = () => `ccp_${nano()}`
export const newConcurrencyEvaluationId = () => `cce_${nano()}`
export const newAbusePreventionPolicyId = () => `abp_${nano()}`
export const newAbuseDetectionEventId = () => `abe_${nano()}`
export const newAbuseAppealId = () => `aba_${nano()}`
export const newFutureTechInterfaceId = () => `fti_${nano()}`
export const newFutureTechRadarItemId = () => `ftr_${nano()}`
export const newCommercialPlanId = () => `cpl_${nano()}`
export const newRevenueStreamId = () => `revn_${nano()}`
export const newCommercialPolicyRuleId = () => `cpr_${nano()}`
export const newOpenSourceComponentId = () => `osc_${nano()}`
export const newGovernanceRoleId = () => `gor_${nano()}`
export const newGovernanceRfcDecisionId = () => `rfc_${nano()}`
export const newContributorPrerequisiteId = () => `cprq_${nano()}`
export const newContributionPolicyId = () => `cpol_${nano()}`
export const newArchitecturePatternId = () => `arcp_${nano()}`
export const newArchitectureInterfaceId = () => `arci_${nano()}`
export const newTechnicalArchitectureEvaluationId = () => `tae_${nano()}`
export const newErrorCodeCatalogId = () => `errc_${nano()}`
export const newEntityStateMachineId = () => `esm_${nano()}`
export const newEntityStateTransitionId = () => `est_${nano()}`
export const newPromptEngineeringGuideId = () => `peg_${nano()}`
export const newPromptAntiPatternRuleId = () => `par_${nano()}`
export const newAgentCommunicationProtocolId = () => `acp_${nano()}`
export const newAgentProtocolMessageId = () => `apm_${nano()}`
export const newStreamProtocolChannelId = () => `spc_${nano()}`
export const newStreamProtocolEventId = () => `spe_${nano()}`
export const newStreamReplayCursorId = () => `src_${nano()}`
export const newToolProtocolManifestId = () => `tpm_${nano()}`
export const newToolProtocolInvocationId = () => `tpi_${nano()}`
export const newToolProtocolResultId = () => `tpr_${nano()}`
export const newSkillId = () => `skill_${nano()}`
export const newSkillInstallFlowId = () => `sif_${nano()}`
export const newSkillSdkManifestId = () => `ssm_${nano()}`
export const newSkillMarketplacePublicationId = () => `smp_${nano()}`
export const newPluginPackageId = () => `plg_${nano()}`
export const newPluginLifecycleEventId = () => `ple_${nano()}`
export const newTeamUserId = () => `tu_${nano()}`
export const newTeamId = () => `team_${nano()}`
export const newTeamMembershipId = () => `tm_${nano()}`
export const newTeamResourceShareId = () => `trs_${nano()}`
export const newTeamApprovalPolicyId = () => `tap_${nano()}`
export const newTeamApprovalDecisionId = () => `tad_${nano()}`
export const newAgentTemplatePackageId = () => `atp_${nano()}`
export const newAgentTemplateInstallId = () => `ati_${nano()}`
export const newTestStrategyItemId = () => `tsi_${nano()}`
export const newTestFixtureSpecId = () => `tfs_${nano()}`
export const newTestFixtureGenerationRunId = () => `tfg_${nano()}`
export const newBenchmarkSuiteId = () => `bms_${nano()}`
export const newBenchmarkCaseId = () => `bmc_${nano()}`
export const newBenchmarkRunId = () => `bmr_${nano()}`
export const newBenchmarkCaseResultId = () => `bcr_${nano()}`
export const newLocalizationSettingsId = () => `locs_${nano()}`
export const newLocalizationResourceId = () => `locr_${nano()}`
export const newAgentLocalizationPolicyId = () => `aloc_${nano()}`
export const newI18nContractCheckId = () => `i18n_${nano()}`
export const newArchitectureEvolutionReservationId = () => `aer_${nano()}`
export const newAgentCloneRecordId = () => `aclone_${nano()}`
export const newAgentComparisonReportId = () => `acmp_${nano()}`
export const newAgentWhatIfAnalysisId = () => `awif_${nano()}`
export const newThemeProfileId = () => `thm_${nano()}`
export const newKeyboardShortcutId = () => `kbs_${nano()}`
export const newAccessibilityProfileId = () => `a11y_${nano()}`
export const newReasonixFileFormatSpecId = () => `rff_${nano()}`
export const newReasonixFileValidationId = () => `rfv_${nano()}`
export const newMigrationWizardSessionId = () => `mws_${nano()}`
export const newMigrationImportRecordId = () => `mir_${nano()}`
export const newPerformanceAnalysisRunId = () => `parun_${nano()}`
export const newPerformanceRecommendationId = () => `prec_${nano()}`
export const newSecurityAuditChecklistItemId = () => `saci_${nano()}`
export const newSecurityAuditRunId = () => `sar_${nano()}`
export const newSecurityAuditRunItemId = () => `sari_${nano()}`
export const newIncidentResponsePlanId = () => `irp_${nano()}`
export const newIncidentReportId = () => `inc_${nano()}`
export const newIncidentResponseActionId = () => `ira_${nano()}`
export const newCapacityPlanningProfileId = () => `cpp_${nano()}`
export const newCapacityPlanningEvaluationId = () => `cpe_${nano()}`
export const newDeprecationPolicyStageId = () => `dps_${nano()}`
export const newFeatureDeprecationId = () => `fdp_${nano()}`
export const newDeprecationMigrationRunId = () => `dmr_${nano()}`
export const newDocumentationSectionId = () => `dsec_${nano()}`
export const newDocumentationPageId = () => `dpg_${nano()}`
export const newHelpCenterSurfaceId = () => `hcs_${nano()}`
export const newHelpCenterItemId = () => `hci_${nano()}`
export const newHelpOnboardingFlowId = () => `hof_${nano()}`
export const newGlossaryTermId = () => `glo_${nano()}`
export const newFaqEntryId = () => `faq_${nano()}`
export const newTroubleshootingEntryId = () => `trb_${nano()}`
export const newQuickReferenceItemId = () => `qri_${nano()}`
export const newNonGoalPolicyId = () => `ngp_${nano()}`
export const newBrandCandidateId = () => `brc_${nano()}`
export const newBrandGuidelineId = () => `brg_${nano()}`
export const newCompetitivePositioningReportId = () => `cprpt_${nano()}`
export const newSuccessMetricDefinitionId = () => `smd_${nano()}`
export const newSuccessMetricSnapshotId = () => `sms_${nano()}`
export const newReadinessChecklistItemId = () => `rci_${nano()}`
export const newOAuthCredentialId = () => `oauth_${nano()}`
export const newOAuthRefreshEventId = () => `oare_${nano()}`
export const newWorkspaceTemplateId = () => `wst_${nano()}`
export const newWorkspaceInitRunId = () => `wir_${nano()}`
export const newCustomModelId = () => `cm_${nano()}`
export const newFinetuneDatasetExportId = () => `fde_${nano()}`
export const newProjectContextId = () => `pc_${nano()}`
export const newProjectAgentRoleId = () => `pgr_${nano()}`
export const newProjectSwitchEventId = () => `pse_${nano()}`
export const newBehaviorSnapshotId = () => `bhs_${nano()}`
export const newBehaviorDriftAnalysisId = () => `bda_${nano()}`
export const newBehaviorStabilizationRunId = () => `bsr_${nano()}`
export const newSkillSynthesisRecordId = () => `ssr_${nano()}`
export const newToolPipelineId = () => `tpl_${nano()}`
export const newUnifiedSearchIndexId = () => `usi_${nano()}`
export const newContextCacheId = () => `ccache_${nano()}`
export const newSoftwareProfileId = () => `sw_${nano()}`
export const newSoftwareCommandId = () => `swc_${nano()}`
export const newSoftwareCommandRunId = () => `swcrun_${nano()}`
export const newRecordedMacroId = () => `mac_${nano()}`
export const newMacroReplayRunId = () => `mrr_${nano()}`
export const newAgentProfileId = () => `ap_${nano()}`
export const newAgentScheduleId = () => `asch_${nano()}`
export const newAgentCertificationExamId = () => `ace_${nano()}`
export const newAgentCertificationRunId = () => `acr_${nano()}`
export const newAgentWorkstationId = () => `aws_${nano()}`
export const newComputerSessionId = () => `cs_${nano()}`
export const newComputerActionEventId = () => `cae_${nano()}`
export const newBrowserSessionId = () => `brs_${nano()}`
export const newBrowserSessionEventId = () => `bse_${nano()}`
export const newMemoryItemId = () => `mem_${nano()}`
export const newMemoryGraphViewId = () => `mgv_${nano()}`
export const newMemoryDecaySnapshotId = () => `mds_${nano()}`
export const newRunReflectionId = () => `rfl_${nano()}`
export const newAgentDiaryEntryId = () => `ade_${nano()}`
export const newContinuationPlanId = () => `ctp_${nano()}`
export const newAgentRetirementPlanId = () => `arp_${nano()}`
export const newKnowledgeTransferPackageId = () => `ktp_${nano()}`
export const newOrganizationalKnowledgeItemId = () => `oki_${nano()}`
export const newOrganizationalLearningReportId = () => `olr_${nano()}`
export const newMetaAgentProfileId = () => `map_${nano()}`
export const newMetaAgentDigestId = () => `mad_${nano()}`
export const newMetaAgentRecommendationId = () => `mar_${nano()}`
export const newLearningEventId = () => `le_${nano()}`
export const newPlaybookId = () => `pb_${nano()}`
export const newPlaybookVersionId = () => `pbv_${nano()}`
export const newWorkflowId = () => `wf_${nano()}`
export const newWorkflowNodeId = () => `wfn_${nano()}`
export const newWorkflowEdgeId = () => `wfe_${nano()}`
export const newWorkflowRunId = () => `wfr_${nano()}`
export const newWorkflowNodeRunId = () => `wnr_${nano()}`
export const newWorkflowPreflightId = () => `wpf_${nano()}`
export const newSimulationRunId = () => `sim_${nano()}`
export const newGoldenTaskSetId = () => `gts_${nano()}`
export const newBacktestRunId = () => `btr_${nano()}`
export const newWorkflowOptimizationId = () => `wopt_${nano()}`
export const newNaturalLanguageWorkflowDraftId = () => `nlwf_${nano()}`
export const newEcosystemRoadmapPhaseId = () => `eco_${nano()}`
export const newEthicalAlignmentPolicyId = () => `ethp_${nano()}`
export const newEthicalAlignmentEvaluationId = () => `ethe_${nano()}`
export const newLegalComplianceFrameworkId = () => `lcf_${nano()}`
export const newLegalDisclaimerNoticeId = () => `ldn_${nano()}`
export const newLicenseComplianceCheckId = () => `lic_${nano()}`
export const newEmotionalUxGuidelineId = () => `eux_${nano()}`
export const newSystemBootstrapCheckId = () => `sbc_${nano()}`
export const newSystemBootstrapRunId = () => `sbr_${nano()}`
export const newTaskTemplateId = () => `tt_${nano()}`
export const newTaskTemplateRunId = () => `ttr_${nano()}`
export const newTaskQueueId = () => `tq_${nano()}`
export const newTaskQueueItemId = () => `tqi_${nano()}`
export const newTaskBatchId = () => `tb_${nano()}`
export const newTaskScheduleId = () => `tsch_${nano()}`
export const newAcceptanceScenarioRunId = () => `ats_${nano()}`
export const newResourceLockId = () => `lock_${nano()}`
export const newOSInterferencePolicyId = () => `osi_${nano()}`
export const newOSInterferenceEventId = () => `osie_${nano()}`
export const newFileSystemBoundaryPolicyId = () => `fsbp_${nano()}`
export const newFileSystemBoundaryEvaluationId = () => `fsbe_${nano()}`
export const newBrowserAutomationTrapPolicyId = () => `batp_${nano()}`
export const newBrowserAutomationTrapEvaluationId = () => `bate_${nano()}`
export const newEnterpriseNetworkPolicyId = () => `enp_${nano()}`
export const newEnterpriseNetworkEvaluationId = () => `ene_${nano()}`
export const newOutputConsistencyPolicyId = () => `ocp_${nano()}`
export const newOutputConsistencyEvaluationId = () => `oce_${nano()}`
export const newResourceGovernorPolicyId = () => `rgp_${nano()}`
export const newResourceGovernorEvaluationId = () => `rge_${nano()}`
export const newGlobalOSIntegrationPolicyId = () => `goip_${nano()}`
export const newGlobalOSIntegrationEvaluationId = () => `goie_${nano()}`
export const newTelemetryPolicyId = () => `tlp_${nano()}`
export const newTelemetryEventId = () => `tle_${nano()}`
export const newTelemetryExportManifestId = () => `tlex_${nano()}`
export const newModelInvocationOptimizationPolicyId = () => `miop_${nano()}`
export const newModelResponseCacheEntryId = () => `mrc_${nano()}`
export const newModelWarmupSessionId = () => `mwu_${nano()}`
export const newModelInvocationOptimizationEventId = () => `mioe_${nano()}`
export const newRuntimeMicroOperationPolicyId = () => `rmop_${nano()}`
export const newRuntimeMicroOperationDecisionId = () => `rmod_${nano()}`
export const newScheduledActionId = () => `sact_${nano()}`
export const newAgentInboxItemId = () => `ainbox_${nano()}`
export const newWorkflowPartialRerunPlanId = () => `wpr_${nano()}`
export const newTaskMergeSuggestionId = () => `tms_${nano()}`
export const newWorkflowTemplateInstantiationId = () => `wti_${nano()}`
export const newApprovalRequestId = () => `apr_${nano()}`
export const newArtifactValidationId = () => `av_${nano()}`
export const newEmployeeRunId = () => `er_${nano()}`
export const newOnboardingSessionId = () => `onb_${nano()}`
export const newEmployeeRunEventId = () => `ere_${nano()}`
export const newRuntimeContextSnapshotId = () => `rcs_${nano()}`
export const newContextWindowVisualizationId = () => `cwv_${nano()}`
export const newRuntimeCheckpointId = () => `chk_${nano()}`
export const newRecoveryEventId = () => `rev_${nano()}`
export const newErrorClassificationId = () => `errc_${nano()}`
export const newRecoveryStrategyAttemptId = () => `rsa_${nano()}`
export const newRecoveryStrategyStatsId = () => `rss_${nano()}`
export const newIdempotencyRecordId = () => `idem_${nano()}`
export const newHumanApprovalPolicyId = () => `hap_${nano()}`
export const newPlanApprovalResultId = () => `plar_${nano()}`
export const newTakeoverSessionId = () => `tko_${nano()}`
export const newUpdatePolicyId = () => `upd_${nano()}`
export const newMaintenanceWindowId = () => `mnt_${nano()}`
export const newCustomMetricProfileId = () => `cmp_${nano()}`
export const newCustomMetricEvaluationId = () => `cme_${nano()}`
export const newInterAgentMessageId = () => `iam_${nano()}`
export const newBlackboardEntryId = () => `bb_${nano()}`
export const newAgentTeamDashboardSnapshotId = () => `atd_${nano()}`
export const newAgentTeamDashboardCommandId = () => `atdc_${nano()}`
export const newCicdIntegrationId = () => `cicd_${nano()}`
export const newCicdRunId = () => `cicdr_${nano()}`
export const newCapabilityNegotiationId = () => `capneg_${nano()}`
export const newCapabilityNegotiationEventId = () => `capne_${nano()}`
export const newConflictResolutionId = () => `cr_${nano()}`
export const newConflictEscalationId = () => `ce_${nano()}`
export const newRealtimeCollabSessionId = () => `rco_${nano()}`
export const newRealtimeSegmentLockId = () => `rsl_${nano()}`
export const newRealtimeEditOperationId = () => `reo_${nano()}`
export const newStyleGuideId = () => `sg_${nano()}`
export const newAgentStyleGuideBindingId = () => `sgb_${nano()}`
export const newAgentDiversityProfileId = () => `adp_${nano()}`
export const newDiversityAnalysisId = () => `dva_${nano()}`
export const newAgentInterviewId = () => `ain_${nano()}`
export const newPerformanceReviewId = () => `prv_${nano()}`
export const newAgentMentorshipId = () => `amt_${nano()}`
export const newAgentMentoringEventId = () => `ame_${nano()}`
export const newUserOverrideId = () => `uov_${nano()}`
export const newBudgetEventId = () => `bud_${nano()}`
export const newDecisionAuditTrailId = () => `dat_${nano()}`
export const newDecisionRollbackId = () => `dbr_${nano()}`
