import { and, desc, eq, type SQL } from 'drizzle-orm'

import { db, schema } from '@/db/client'
import type {
  JsonObject,
  LegalComplianceFrameworkRow,
  LegalComplianceStatus,
  LegalDisclaimerNoticeRow,
  LegalDisclaimerPlacement,
  LicenseComplianceCheckRow,
  LicenseRiskLevel,
} from '@/db/schema'
import {
  newLegalComplianceFrameworkId,
  newLegalDisclaimerNoticeId,
  newLicenseComplianceCheckId,
} from '@/server/ids'

export interface CreateLegalComplianceFrameworkArgs {
  name?: string
  regulations?: JsonObject
  dataResidencyDefault?: string
  notes?: string
  status?: LegalComplianceStatus
}

export interface CreateLegalDisclaimerNoticeArgs {
  placement: LegalDisclaimerPlacement
  title: string
  message: string
  requiresAcknowledgement?: boolean
  status?: LegalComplianceStatus
}

export interface LicenseComplianceCheckArgs {
  code?: string
  source: string
  declaredLicense?: string
}

const defaultRegulations: JsonObject = {
  gdpr: {
    applies: false,
    dataProcessingAgreement: false,
    rightToAccess: true,
    rightToBeForgotten: true,
    dataResidency: 'local_only',
  },
  ccpa: {
    applies: false,
    optOutOfSale: true,
    dataDisclosure: true,
  },
  hipaa: {
    applies: false,
  },
  pipl: {
    applies: false,
    dataLocalization: true,
    consentRequired: true,
  },
}

const defaultDisclaimerNotices: CreateLegalDisclaimerNoticeArgs[] = [
  {
    placement: 'installation',
    title: 'AI computer operation responsibility',
    message:
      'This system allows AI Agents to operate your computer. Grant only necessary permissions, back up important files before execution, do not approve high-risk actions you do not understand, and you are responsible for your use of the system.',
    requiresAcknowledgement: true,
    status: 'active',
  },
  {
    placement: 'agent_creation',
    title: 'Agent capability warning',
    message:
      'You are about to create an Agent that may read files, write files, operate a browser, or run commands. Start with probation mode before increasing autonomy.',
    requiresAcknowledgement: true,
    status: 'active',
  },
  {
    placement: 'approval_footer',
    title: 'Approval consequence',
    message:
      'After approval, the Agent will perform the actual operation. If this action is unexpected, reject it.',
    requiresAcknowledgement: false,
    status: 'active',
  },
  {
    placement: 'artifact_output',
    title: 'AI-generated artifact notice',
    message:
      'This content was generated by an AI Agent and has not been manually reviewed. Verify accuracy and safety before use.',
    requiresAcknowledgement: false,
    status: 'active',
  },
]

export function getDefaultLegalDisclaimerNoticeCount(): number {
  return defaultDisclaimerNotices.length
}

export async function seedLegalCompliance(): Promise<{
  framework: LegalComplianceFrameworkRow
  notices: LegalDisclaimerNoticeRow[]
}> {
  const framework = await seedLegalComplianceFramework()
  const notices: LegalDisclaimerNoticeRow[] = []
  for (const notice of defaultDisclaimerNotices) {
    const existing = await db.query.legalDisclaimerNotices.findFirst({
      where: eq(schema.legalDisclaimerNotices.placement, notice.placement),
    })
    if (existing) {
      notices.push(existing)
      continue
    }
    notices.push(await createLegalDisclaimerNotice(notice))
  }
  return { framework, notices }
}

export async function seedLegalComplianceFramework(): Promise<LegalComplianceFrameworkRow> {
  const existing = await db.query.legalComplianceFrameworks.findFirst({
    where: eq(schema.legalComplianceFrameworks.name, 'Default Local-First Compliance Matrix'),
  })
  if (existing) return existing
  return createLegalComplianceFramework({
    name: 'Default Local-First Compliance Matrix',
    regulations: defaultRegulations,
    dataResidencyDefault: 'local_only',
    notes:
      'Local-first baseline for GDPR, CCPA, HIPAA, and PIPL readiness. This is product control-plane metadata, not legal advice.',
    status: 'active',
  })
}

export async function createLegalComplianceFramework(
  args: CreateLegalComplianceFrameworkArgs = {},
): Promise<LegalComplianceFrameworkRow> {
  const now = Date.now()
  const row = {
    id: newLegalComplianceFrameworkId(),
    name: args.name?.trim() || 'Legal Compliance Framework',
    regulations: args.regulations ?? defaultRegulations,
    dataResidencyDefault: args.dataResidencyDefault?.trim() || 'local_only',
    notes: args.notes?.trim() || '',
    status: args.status ?? 'active',
    createdAt: now,
    updatedAt: now,
  }
  await db.insert(schema.legalComplianceFrameworks).values(row)
  return row
}

export async function listLegalComplianceFrameworks(args: {
  status?: LegalComplianceStatus
  limit?: number
} = {}): Promise<LegalComplianceFrameworkRow[]> {
  const conditions: SQL[] = []
  if (args.status) conditions.push(eq(schema.legalComplianceFrameworks.status, args.status))
  return db.query.legalComplianceFrameworks.findMany({
    where: conditions.length ? and(...conditions) : undefined,
    orderBy: [desc(schema.legalComplianceFrameworks.updatedAt)],
    limit: args.limit ?? 50,
  })
}

export async function createLegalDisclaimerNotice(
  args: CreateLegalDisclaimerNoticeArgs,
): Promise<LegalDisclaimerNoticeRow> {
  const now = Date.now()
  const row = {
    id: newLegalDisclaimerNoticeId(),
    placement: args.placement,
    title: args.title.trim(),
    message: args.message.trim(),
    requiresAcknowledgement: args.requiresAcknowledgement ?? false,
    status: args.status ?? 'active',
    createdAt: now,
    updatedAt: now,
  }
  await db.insert(schema.legalDisclaimerNotices).values(row)
  return row
}

export async function listLegalDisclaimerNotices(args: {
  placement?: LegalDisclaimerPlacement
  status?: LegalComplianceStatus
  limit?: number
} = {}): Promise<LegalDisclaimerNoticeRow[]> {
  const conditions: SQL[] = []
  if (args.placement) conditions.push(eq(schema.legalDisclaimerNotices.placement, args.placement))
  if (args.status) conditions.push(eq(schema.legalDisclaimerNotices.status, args.status))
  return db.query.legalDisclaimerNotices.findMany({
    where: conditions.length ? and(...conditions) : undefined,
    orderBy: [desc(schema.legalDisclaimerNotices.updatedAt)],
    limit: args.limit ?? 50,
  })
}

export async function detectLicenseCompliance(
  args: LicenseComplianceCheckArgs,
): Promise<LicenseComplianceCheckRow> {
  const license = normalizeLicense(args.declaredLicense || inferLicense(args.code ?? '', args.source))
  const { obligations, restrictions, riskLevel } = licenseProfile(license)
  const row = {
    id: newLicenseComplianceCheckId(),
    source: args.source.trim(),
    license,
    obligations,
    restrictions,
    riskLevel,
    attributionText: generateAttributionText(args.source, license, obligations),
    createdAt: Date.now(),
  }
  await db.insert(schema.licenseComplianceChecks).values(row)
  return row
}

export async function listLicenseComplianceChecks(args: {
  license?: string
  riskLevel?: LicenseRiskLevel
  limit?: number
} = {}): Promise<LicenseComplianceCheckRow[]> {
  const conditions: SQL[] = []
  if (args.license) conditions.push(eq(schema.licenseComplianceChecks.license, args.license))
  if (args.riskLevel) conditions.push(eq(schema.licenseComplianceChecks.riskLevel, args.riskLevel))
  return db.query.licenseComplianceChecks.findMany({
    where: conditions.length ? and(...conditions) : undefined,
    orderBy: [desc(schema.licenseComplianceChecks.createdAt)],
    limit: args.limit ?? 50,
  })
}

function inferLicense(code: string, source: string): string {
  const text = `${source}\n${code}`.toLowerCase()
  if (text.includes('apache-2.0') || text.includes('apache license')) return 'Apache-2.0'
  if (text.includes('gpl-3.0') || text.includes('gnu general public license')) return 'GPL-3.0'
  if (text.includes('bsd')) return 'BSD'
  if (text.includes('mit license') || text.includes('permission is hereby granted')) return 'MIT'
  return 'unknown'
}

function normalizeLicense(license: string): string {
  const value = license.trim()
  if (!value) return 'unknown'
  const lower = value.toLowerCase()
  if (lower === 'mit') return 'MIT'
  if (lower === 'apache' || lower === 'apache-2.0') return 'Apache-2.0'
  if (lower === 'gpl' || lower === 'gpl-3.0') return 'GPL-3.0'
  if (lower === 'bsd') return 'BSD'
  return value
}

function licenseProfile(license: string): {
  obligations: string[]
  restrictions: string[]
  riskLevel: LicenseRiskLevel
} {
  if (license === 'MIT') {
    return {
      obligations: ['preserve_copyright_notice', 'include_license_text'],
      restrictions: [],
      riskLevel: 'low',
    }
  }
  if (license === 'Apache-2.0') {
    return {
      obligations: ['preserve_copyright_notice', 'include_license_text', 'state_significant_changes'],
      restrictions: ['respect_patent_license_terms'],
      riskLevel: 'low',
    }
  }
  if (license === 'BSD') {
    return {
      obligations: ['preserve_copyright_notice', 'include_license_text'],
      restrictions: ['do_not_use_author_names_for_endorsement'],
      riskLevel: 'medium',
    }
  }
  if (license === 'GPL-3.0') {
    return {
      obligations: ['preserve_copyright_notice', 'include_license_text', 'provide_corresponding_source'],
      restrictions: ['copyleft_obligations_for_distribution', 'review_before_closed_source_use'],
      riskLevel: 'high',
    }
  }
  return {
    obligations: ['verify_license_before_reuse'],
    restrictions: ['do_not_reuse_without_review'],
    riskLevel: 'critical',
  }
}

function generateAttributionText(source: string, license: string, obligations: string[]): string {
  return `Source: ${source}; license: ${license}; obligations: ${obligations.join(', ')}.`
}
